package com.omar.calendar.domain.entity;

import java.io.Serializable;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.NonNull;
import lombok.RequiredArgsConstructor;
import lombok.Setter;
import lombok.experimental.Accessors;
import org.hibernate.annotations.GenericGenerator;

@Entity
@Table(name = "EVENT")
@Data @Accessors(fluent = true)
@NoArgsConstructor
@AllArgsConstructor
@RequiredArgsConstructor
public class Event implements Serializable {

    /** Event Id and PK, autogenerated */
    @GeneratedValue(generator="increment")
    @GenericGenerator(name="increment", strategy = "increment")
    private @Id @Setter(AccessLevel.PRIVATE) Long id;

    /** The id of the calendar this event is attached to */
    private @NonNull String calendarName;

    /** The event title */
    private @NonNull String title;

    /** The event location */
    private @NonNull String location;

    /** The event date, String format YYYY-MM-DD */
    private @NonNull String eventDate;

    /** The event start time, String format HH24-MM-SS */
    private @NonNull String startTime;

    /** The event end time, String format HH24-MM-SS */
    private @NonNull String endTime;

    /** The event attendees list as a comma separated user ids */
    private @NonNull String attendees;

    /** The date and time the event reminder will is sent. String format HH24-MM-SS */
    private @NonNull String reminderTime;

    /** Indicates whether reminder was sent Y/N*/
    private @NonNull String isReminderSent;

}


