org.gradle.jvmargs=-Djava.net.preferIPv4Stack=true -Dsun.net.inetaddr.ttl=0 -Dsun.net.inetaddr.negative.ttl=0
systemProp.https.proxyHost=21.0.0.53
systemProp.https.proxyPort=15002
systemProp.https.proxyUser=container_container_011CUMJnr8jrbqcw52CvN5SS--kindly-juicy-fast-dyes
systemProp.https.proxyPassword=noauth
systemProp.http.proxyHost=21.0.0.53
systemProp.http.proxyPort=15002
systemProp.http.proxyUser=container_container_011CUMJnr8jrbqcw52CvN5SS--kindly-juicy-fast-dyes
systemProp.http.proxyPassword=noauth
systemProp.http.nonProxyHosts=localhost|127.0.0.1|169.254.169.254|metadata.google.internal|*.svc.cluster.local|*.local|*.googleapis.com|*.google.com
