plugins {
    id 'java'
    id 'idea'
    id 'org.springframework.boot' version '3.5.6'
    id 'io.spring.dependency-management' version '1.1.7'
}

description = 'Calendar Service'

repositories {
    mavenCentral()
}

compileJava.dependsOn(processResources)

ext {
    lombokVersion = '1.18.36'
}

dependencies {
    /* Actuator */
    implementation 'org.springframework.boot:spring-boot-starter-actuator'

    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
    compileOnly "org.springframework.boot:spring-boot-configuration-processor"
    annotationProcessor "org.projectlombok:lombok:${lombokVersion}"

    developmentOnly("org.springframework.boot:spring-boot-devtools")

    implementation project(':calendar-api')
    //implementation project(':calendar-util')

    implementation('org.springframework.boot:spring-boot-starter-data-jpa')
    implementation('org.springframework.boot:spring-boot-starter-web')
    compileOnly "org.projectlombok:lombok:${lombokVersion}"
    implementation "org.springdoc:springdoc-openapi-starter-webmvc-ui:2.7.0"
    implementation('org.springframework.boot:spring-boot-starter-validation')
    testImplementation('org.springframework.boot:spring-boot-starter-test')
    runtimeOnly('org.hsqldb:hsqldb')
    //testImplementation('org.springframework.security:spring-security-test')
    //implementation('org.springframework.boot:spring-boot-starter-security')

    /*  AOP and Aspect */
    implementation('org.springframework.boot:spring-boot-starter-aop')

    /* Distributed logging - Sleuth has been replaced by Micrometer Tracing */
    implementation('io.micrometer:micrometer-tracing-bridge-brave')
    implementation('io.zipkin.reporter2:zipkin-reporter-brave')
    implementation "org.springframework.amqp:spring-rabbit"

    /* Circuit Breaker - Hystrix has been replaced by Resilience4J */
    implementation('io.github.resilience4j:resilience4j-spring-boot3:2.2.0')
    implementation('org.springframework.boot:spring-boot-starter-aop')

    /* Eureka */
    //implementation('org.springframework.cloud:spring-cloud-starter-netflix-eureka-client')
    //implementation('org.springframework.cloud:spring-cloud-starter-netflix-eureka-server')

}

ext {
    springCloudVersion = '2025.0.0'
}
dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}
